### PR TITLE
Improve "Getting Started" guide

### PR DESCRIPTION
**Pull request by olivier-grech**
I created a better "Getting Started" guide, and clearly separated it from the installation guide.

### CODE REVIEW

**Comment by abledbody** [comment]
While "demo game" is technically correct, for the sake of consistent terminology I feel like you should make the distinction between a demo and a game more clear, like how there's both install_demos and install_games.

**Comment by olivier-grech** [comment]
Just to make sure, you are suggesting to replace every instance of "demo game" by "demo", right?

**Comment by abledbody** [comment]
Something like that. Use your discretion.

**Comment by olivier-grech** [comment]
I made a commit to use a consistent terminology.

**Review by Rami-Sabbagh — APPROVED** [review]
Awesome changes !
Thanks for your efforts :)

**Pull request merged**
